java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    PNC_SERVICE_HOST: juror-pnc.ithc.platform.hmcts.net
    JUROR_SERVICE_HOST: juror-api.ithc.platform.hmcts.net
    JOB_EXECUTION_SERVICE_HOST: juror-scheduler-execution.ithc.platform.hmcts.net
    #The following may need updating with NLE values (as initially taken from development)
    PNC_SERVICE_PNC_TRAN_CODE: LO
    PNC_SERVICE_REASON_CODE: 6
    PNC_SERVICE_PNC_TERMINAL: 2LCRTS001
    PNC_SERVICE_PNC_USERID: 2KCRTS01
    PNC_SERVICE_PNC_MODE: TRNG
    PNC_SERVICE_PNC_AUTHORISATION: 2L01MJ01
    PNC_SERVICE_ORIGINATOR: 'MOJ JUROR VETTING'
    PNC_SERVICE_GATEWAY_ID: MJCRT001
    PNC_SERVICE_REQUEST_LOCATION: MOJCGI
