java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    #The following have been updated with production values
    PNC_SERVICE_PNC_TRAN_CODE: '#LO'
    PNC_SERVICE_REASON_CODE: 6
    PNC_SERVICE_PNC_TERMINAL: LCRTS001
    PNC_SERVICE_PNC_USERID: 2KCRTS01
    PNC_SERVICE_PNC_MODE: LIVE
    PNC_SERVICE_PNC_AUTHORISATION: 2K01JV01
    PNC_SERVICE_ORIGINATOR: 'MOJ JUROR VETTING'
    PNC_SERVICE_GATEWAY_ID: JVJVS001
    PNC_SERVICE_REQUEST_LOCATION: MOJCGI
